import esbuild from "esbuild";
import process from "process";
import { copyFileSync, mkdirSync, watch as fsWatch } from "fs";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

let prod = process.argv[2] === 'production';
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules],
	format: 'cjs',
	target: 'ES6',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'build/main.js',
});

mkdirSync('build', { recursive: true });
copyFileSync('src/styles.css', 'build/styles.css');
copyFileSync('manifest.json', 'build/manifest.json');

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	fsWatch('src/styles.css', () => {
		copyFileSync('src/styles.css', 'build/styles.css');
		console.log('build/styles.css updated');
	});
	fsWatch('manifest.json', () => {
		copyFileSync('manifest.json', 'build/manifest.json');
		console.log('build/manifest.json updated');
	});
}
